### ISSUE TITLE
[Proposal] Get the package include in the Online Package Manager.

### ISSUE THREAD

**Issue by gcarreno** [terrylao/PascalContainer#11]
Hey Terry(@terrylao),

As promised.

Now, are you OK with having the code in the current state included in the OPM?

I'm gonna ask on the [Lazarus Forums](https://forum.lazarus.freepascal.org/) what is the process of having a package made ready to be on the OPM and then I'll report back here.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Terry(@terrylao),

I've posted the question here: https://forum.lazarus.freepascal.org/index.php/topic,34297.msg413426.html#msg413426

Let's see what GetMem has to say :)

Cheers,
Gus

**Comment by terrylao** [comment]
no i have not yet get how to implement iterator, 
because the sample of lazarus wiki was for general object, not for generic.
and i had test for generic, but FPC report an strange number error.

**Comment by gcarreno** [comment]
Hey Terry(@terrylao),

> no i have not yet get how to implement iterator,

No probs. I'll let you get around that issue and when GetMem replies we'll have a good example on how to proceed in the future!!

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Terry(@terrylao),

As you can see by reading [this answer](https://forum.lazarus.freepascal.org/index.php/topic,34297.msg413431.html#msg413431) from GetMem, it's easy to get it on `OPM`.

In my answer I suggested that you tag, release and then you get it on `OPM`. That way that release should be considered stable.

I also mentioned that you still need to address the Iterator issue.

We'll all be waiting for that :wink:

I'll leave this issue open as long as we need it :wink: !!

Cheers,
Gus

**Comment by terrylao** [comment]
any action do i have to take to move to OPM?

**Comment by gcarreno** [comment]
Hey Terry(@terrylao),

I'm not the expert on how to get a package onto OPM.

I would advise you to post your question on how to list this package under the OPM on this thread:
[**Online Package Manager** on the Lazarus Forums](https://forum.lazarus.freepascal.org/index.php/topic,34297.0.html)

GetMem, the person behind OPM, will be the one to listen to when you want to know how to list your package under the OPM.

Hope this helps :smiley: 

Cheers,
Gus
