### ISSUE TITLE
hashmap not working with long keys

### ISSUE THREAD

**Issue by benibela** [terrylao/PascalContainer#2]
This prints `123 0`
```

program Project1;

{$mode objfpc}{$H+}

uses CodaMinaHashMap;

type TCMHM = specialize TCodaMinaHashMap<string, integer>;
var cm: TCMHM;
begin
  cm := TCMHM.create;
  cm.add('abcdefgh', 123);
  cm.add('abcdefghi', 123456);
  writeln(cm['abcdefgh'], ' ', cm['abcdefghi']);
  cm.free;
end.


```

fpc trunk, 64-bit, linux (after removing the = in #1)

**Comment by terrylao** [comment]
the same code i can run correctly in Windows7/windows 10 64 bit FPC。
any other more information

**Comment by benibela** [comment]
Weird. Now it is working. Perhaps it depends on some compiler settings.

But now this prints 0 at the end:

```
program Project1;

{$mode objfpc}{$H+}

uses CodaMinaHashMap;

type TCMHM = specialize TCodaMinaHashMap<string, integer>;
var cm: TCMHM;
  s: string;
begin
  cm := TCMHM.create;
  cm.add('abcdefgh', 123);
  cm.add('abcdefghi', 123456);
  writeln(cm['abcdefgh']);
  writeln(cm['abcdefghi']);
  s := 'abcdefgh';
  writeln(cm[s + 'i']);
  cm.free;
end.
```

It does not recognizing the strings as strings. Probably it needs  `{$H+}`, otherwise string means shortstring

**Comment by terrylao** [comment]
my implementation is checking the generic type of "string" or not

**Comment by benibela** [comment]
It is still failing with some keys longer than 48 bytes in my benchmark.

For example with the key `#$8D#$96#$AF#$C8#$98#$CB#$8C#$C9#$74#$9C#$A1#$6C#$77#$5B#$D2#$2B#$E0#$56#$6C#$7F#$BE#$C2#$89#$7F#$91#$6E#$D9#$C7#$2E#$63#$31#$A1#$24#$69#$C6#$DF#$BB#$3C#$CE#$CE#$E3#$7E#$BF#$C0#$7C#$20#$20#$20#$21`.

Although when I try to make a small example, it is working there

**Comment by benibela** [comment]
Oh, I was compiling it wrongly. There was another `murmur3.pas` in the search path, and it has been using that one and not your `murmur3.pas`.
