### ISSUE TITLE
32-bit support

### ISSUE THREAD

**Issue by benibela** [terrylao/PascalContainer#3]
The pointer/length calculation in CodaMinaHashMap `pcrd:=@data[-8]; len  := pcrd[0];` only works on 64-bit systems
        `

**Comment by terrylao** [comment]
i have no 32 bit environment, but you can try to pcrd:=@data[-4]; len :=
pcrd[0];

**Comment by terrylao** [comment]
install the addon of lazarus for win32, and do the setting below:
targetOS=Win32
target CPU Family = i386
Target processor = default

with  pcrd:=@data[-8]; len := pcrd[0]; 
exe file run in WIN7 64 bit, run work corretly.

**Comment by terrylao** [comment]
use the native length() for fetching the length of string.
