### ISSUE TITLE
[Question] This is more due to curiosity than an issue itself

### ISSUE THREAD

**Issue by gcarreno** [terrylao/PascalContainer#5]
Hey Terry(@terrylao),

If you look at this picture:

![PascalContainer-project1-missing-files](https://user-images.githubusercontent.com/81799/127079474-09de3ff8-f08b-4cca-9a2a-9e4c49cd1587.png)

There's a lot of files missing from the project.

Is it OK if I ask what they are?

Many thanks in advance, Terry!!

Cheers,
Gus

**Comment by terrylao** [comment]
it is ok, genericcollections was not in FPC default package,
others was temporary files.

**Comment by gcarreno** [comment]
Hey Terry(@terrylao),

Okies I get it. So that's code from when FPC was lacking Generics so you had to get them from somewhere else.

Gotcha!!

Cheers,
Gus

**Comment by terrylao** [comment]
Those files are not related to my publication, just related to when I
developed them.

**Comment by gcarreno** [comment]
Hey Terry(@terrylao),

Cool, cool, I get ya :)

Cheers,
Gus
