### ISSUE TITLE
[Question] Change the folder structure and make it a runtime only package?

### ISSUE THREAD

**Issue by gcarreno** [terrylao/PascalContainer#7]
Hey Terry(@terrylao),

This is gonna seem a lot like invasion on your project, but may I be so bold as to suggest moving your code around like this:

```
-+- bin // Ignored by GIT and where all binary files will drop: *.o, *.ppu, *.obj, *.compiled etc
 +- src // Folder that will contain all the code
 |`- CodaMina*.pas
 |`- genericCodaMina*.pas
 |`- murmur3.pas
 +- packages // Folder that contains the package files
 |`- pascalcontainer.lpk
 `- testing // Folder for you testing program
  `- project1.lpi
  `- project.lpr
 ```

And making the whole lib a runtime only package that we can install on the IDE?

We can even list it on the OPM if you think your code is worthy :)

Cheers,
Gus

**Comment by terrylao** [comment]
During development, there are so many temporary files, and I am not making
a clean project when I publish my code.
I just want to show that Pascal also has a good container.
all my code was tested within my own project.
So are they worthy?
I have no idea, at least, for HashMap, it is fast enough , for the Tree
series, their correctness was confirmed.
Sorting algorithms are also tested and performance is compared to C.

**Comment by gcarreno** [comment]
Hey Terry(@terrylao),

I quite sure that your code is worthy of being in OPM(Online Package Manager). And doubly so because your sorting _algos_ are comparable to C :wink: 

But the question was: Can I transform your project into what I listed on the original message?

Cheers,
Gus

**Comment by terrylao** [comment]
But the question was: Can I transform your project into what I listed on
the original message?
ans: sure. and thanks

**Comment by gcarreno** [comment]
Hey Terry(@terrylao),

> ans: sure. and thanks

There is no need to thank me!!
Actually, I'm the one that is overwhelmingly grateful since I'm doing so much change in your work and you said **yes**.

So: Thank **YOU**!!

Gimme an hour and I'll have the repo all changed and working like before!!

Once I get all the folders done, I'll add the package and then we can talk about listing it on OPM, ok?

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Terry(@terrylao),

Okies, I've created the PR with the folder structure change.

After you accept that one and I pull all the changes into my forked one, I'll create another PR with the package :)

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Terry(@terrylao),

All done: The package has been added.

Let me do some more testing and if all is good, I'll close this issue and you can resume your work on it :)

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Terry(@terrylao),

I've tested the package on a completely different project, a GUI one, and all is working fine.

This concludes all the changes that I was thinking of and I'll create a new Issue for us to discuss the inclusion on the OPM and I'll close this one.

Cheers,
Gus

**Comment by terrylao** [comment]
Thanks, maybe in the future I will add an iterator for those containers.
but the current test for generic, it looks has some problems that need to
be solved.
